Supriya BH-AMB2273

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("Social_Network_Ads.csv")
print(data)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values

In [ ]:
print(data.columns[[2,3]])

Index(['Age', 'EstimatedSalary'], dtype='object')


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_Train=sc_x.fit_transform(x_train)
x_Test=sc_x.transform(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="entropy",max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(x_Train,y_train)
print(model)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)


In [ ]:
y_pred_dec=model.predict(x_Test)
print(y_pred_dec)

[0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 0 0
 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1]


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)

[[79  6]
 [ 8 41]]


In [ ]:
from sklearn.metrics import accuracy_score
print("Decision Tree",accuracy_score(y_test,y_pred_dec))

Decision Tree 0.8955223880597015


In [ ]:
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression()
modellr.fit(x_Train,y_train)
print(modellr)


LogisticRegression()


In [ ]:
y_pred=modellr.predict(x_Test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0
 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 0 0 1 0 1]


In [ ]:
from sklearn.metrics import confusion_matrix
cmlr=confusion_matrix(y_test,y_pred)
print(cmlr)

[[79  6]
 [11 38]]


In [ ]:
from sklearn.metrics import accuracy_score
print("Logistic Regression",accuracy_score(y_test,y_pred))

Logistic Regression 0.8731343283582089


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion='entropy',random_state=0)
RFmodel.fit(x_Train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)

In [ ]:
y_pred_rf=RFmodel.predict(x_Test)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)

[[79  6]
 [ 7 42]]


In [ ]:
from sklearn.metrics import accuracy_score
print("Random forest",accuracy_score(y_test,y_pred_rf))

Random forest 0.9029850746268657


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_Train,y_train)
y_pred_nb = nb.predict(x_Test)
cmnb = confusion_matrix(y_test, y_pred_nb)
print(cmnb)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)

[[80  5]
 [ 8 41]]
Accuracy: 0.9029850746268657


In [ ]:
from sklearn.svm import SVC  #svc-classifier svr-regression
#creats SVM classifier object
#model=SVC(kernel='rbf/linear',C=1.0,gama='scale',random_state=0)
model=SVC(kernel='poly',degree=3)
model.fit(X_Train,y_train)
print(model)
y_pred_svc= model.predict(x_Test) # Changed 'svc' to 'model'
cmsvc = confusion_matrix(y_test, y_pred_svc)
print(cmsvc)
accuracy_svc= accuracy_score(y_test, y_pred_svc)
print("Accuracy:", accuracy_svc)

NameError: name 'X_Train' is not defined

In [ ]:
y_pred_nb = nb.predict(x_Test)
cmnb = confusion_matrix(y_test, y_pred_nb)
print(cmnb)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)

NameError: name 'nb' is not defined